(() => {
'use strict';
const KEY='soundpulse', DEF={enabled:true,widget:true,awareness:true,mode:'auto',reaction:'natural',dynamicColor:true,collapsed:true,x:null,y:null};
let S,T=null,drag=false,moved=false,off={x:0,y:0};
const C=()=>SillyTavern.getContext(), save=()=>C().saveSettingsDebounced();
function settings(){let e=C().extensionSettings;e[KEY]??=structuredClone(DEF);for(const k in DEF)if(e[KEY][k]===undefined)e[KEY][k]=DEF[k];return e[KEY]}
const spotify=()=>C().extensionSettings?.spotify||null;
async function refresh(sp){let t=sp?.clientToken;if(!sp?.clientId||!t?.refresh_token)return false;if((t.expires||0)>Date.now()+180000)return true;try{let r=await fetch('https://accounts.spotify.com/api/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'refresh_token',refresh_token:t.refresh_token,client_id:sp.clientId})});if(!r.ok)return false;let n=await r.json();sp.clientToken={...t,...n,refresh_token:n.refresh_token||t.refresh_token,expires:Date.now()+(n.expires_in||3600)*1000};save();return true}catch{return false}}
async function api(path,opt={}){let sp=spotify();if(!sp?.clientToken?.access_token)return null;await refresh(sp);let r=await fetch('https://api.spotify.com/v1/'+path,{...opt,headers:{Authorization:'Bearer '+sp.clientToken.access_token,'Content-Type':'application/json'}});if(r.status===204)return {};if(!r.ok)throw Error('Spotify '+r.status);return r.json()}
async function poll(){if(!S.enabled)return;try{let p=await api('me/player/currently-playing');if(!p?.item){T=null;render();return}let i=p.item;T={name:i.name,artist:(i.artists||[]).map(a=>a.name).join(', '),cover:i.album?.images?.[0]?.url||'',duration:i.duration_ms||0,progress:p.progress_ms||0,playing:!!p.is_playing,at:Date.now()};render()}catch(e){console.debug('[SoundPulse]',e);T=null;render(true)}}
function prog(){return T?Math.max(0,Math.min(T.duration,T.progress+(T.playing?Date.now()-T.at:0))):0}
function fmt(ms){let s=Math.floor(ms/1000);return Math.floor(s/60)+':'+String(s%60).padStart(2,'0')}
function inject(){let k='soundpulse_awareness';if(!S.enabled||!S.awareness||!T||S.mode==='visual'){C().setExtensionPrompt(k,'',-1,0);return}let x=`[SOUNDPULSE — LIVE MUSIC CONTEXT]
The user is actually listening to: ${T.name} — ${T.artist}.
Mode: ${S.mode}. Reaction level: ${S.reaction}.
If AUTO, decide whether the track plausibly exists in-world or is only a soundtrack. Song language need not match the setting language. If characters could not plausibly hear or know it, never pretend they do; use only broad emotional atmosphere when relevant. If it plausibly exists in-world, characters may notice it naturally. Never force a reference or derail a stronger scene.`;C().setExtensionPrompt(k,x,0,0,false,0)}
function tint(url){if(!S.dynamicColor||!url)return;let im=new Image();im.crossOrigin='anonymous';im.onload=()=>{try{let c=document.createElement('canvas');c.width=c.height=1;let g=c.getContext('2d');g.drawImage(im,0,0,1,1);let d=g.getImageData(0,0,1,1).data;document.documentElement.style.setProperty('--sp-accent',`rgb(${Math.max(90,d[0])} ${Math.max(70,d[1])} ${Math.max(120,d[2])})`)}catch{}};im.src=url}
function widget(){if(document.querySelector('#soundpulse-widget'))return;let e=document.createElement('div');e.id='soundpulse-widget';e.innerHTML=`<button class="sp-vinyl"><span class="sp-disc"><span class="sp-label">♪</span></span><span class="sp-bars">${'<i></i>'.repeat(5)}</span></button><section class="sp-panel"><div class="sp-art"><img><span class="sp-mini"></span></div><main><small>NOW PLAYING</small><strong>Spotify ждёт музыку…</strong><em></em><div class="sp-progress"><b></b></div><div class="sp-time"><span>0:00</span><span>0:00</span></div><div class="sp-actions"><button data-a="prev">⏮</button><button data-a="play">▶</button><button data-a="next">⏭</button><button data-a="mode">AUTO</button></div><div class="sp-lyrics">♪ lyrics · место для текущей строки</div></main></section>`;document.body.appendChild(e);
e.querySelector('.sp-vinyl').onclick=()=>{if(moved){moved=false;return}S.collapsed=!S.collapsed;save();render()};
e.querySelectorAll('[data-a]').forEach(b=>b.onclick=async ev=>{ev.stopPropagation();let a=b.dataset.a;if(a==='mode'){let m=['auto','inworld','soundtrack','visual'];S.mode=m[(m.indexOf(S.mode)+1)%m.length];save();render();return}try{if(a==='prev')await api('me/player/previous',{method:'POST'});if(a==='next')await api('me/player/next',{method:'POST'});if(a==='play')await api(T?.playing?'me/player/pause':'me/player/play',{method:'PUT'});setTimeout(poll,500)}catch(e){console.debug(e)}});
e.addEventListener('pointerdown',ev=>{if(ev.target.closest('.sp-panel button'))return;drag=true;moved=false;let r=e.getBoundingClientRect();off={x:ev.clientX-r.left,y:ev.clientY-r.top}});
e.addEventListener('pointermove',ev=>{if(!drag)return;moved=true;let x=Math.max(4,Math.min(innerWidth-e.offsetWidth-4,ev.clientX-off.x)),y=Math.max(4,Math.min(innerHeight-e.offsetHeight-4,ev.clientY-off.y));Object.assign(e.style,{left:x+'px',top:y+'px',right:'auto',bottom:'auto'});S.x=x;S.y=y});
e.addEventListener('pointerup',()=>{if(drag){drag=false;save()}});
if(S.x!=null)Object.assign(e.style,{left:S.x+'px',top:S.y+'px',right:'auto',bottom:'auto'})}
function render(err=false){widget();let e=document.querySelector('#soundpulse-widget');e.style.display=S.widget?'flex':'none';e.classList.toggle('sp-collapsed',S.collapsed);e.classList.toggle('sp-playing',!!T?.playing);let title=e.querySelector('strong'),artist=e.querySelector('em'),img=e.querySelector('.sp-art img');if(T){title.textContent=T.name;artist.textContent=T.artist;img.src=T.cover;img.style.display=T.cover?'block':'none';tint(T.cover);e.querySelector('[data-a=mode]').textContent=({auto:'AUTO',inworld:'IN-WORLD',soundtrack:'SOUNDTRACK',visual:'VISUAL'}[S.mode]);e.querySelector('[data-a=play]').textContent=T.playing?'❚❚':'▶'}else{title.textContent=err?'Spotify: нет соединения':'Spotify ждёт музыку…';artist.textContent=spotify()?.clientToken?'Ничего не играет':'Spotify → Authenticate';img.style.display='none'}inject()}
function tick(){let e=document.querySelector('#soundpulse-widget');if(!e||!T)return;let p=prog();e.querySelector('.sp-progress b').style.width=(T.duration?p/T.duration*100:0)+'%';let s=e.querySelectorAll('.sp-time span');s[0].textContent=fmt(p);s[1].textContent=fmt(T.duration)}
function ui(){let h=document.querySelector('#extensions_settings2');if(!h||document.querySelector('#soundpulse-settings'))return;let d=document.createElement('div');d.id='soundpulse-settings';d.className='inline-drawer';d.innerHTML=`<div class="inline-drawer-toggle inline-drawer-header"><b>🎧 SoundPulse · 0.1.0</b><div class="inline-drawer-icon fa-solid fa-circle-chevron-down down"></div></div><div class="inline-drawer-content"><label class="checkbox_label"><input id="spe" type="checkbox"><span>Включить SoundPulse</span></label><label class="checkbox_label"><input id="spw" type="checkbox"><span>Плавающий винил</span></label><label class="checkbox_label"><input id="spa" type="checkbox"><span>Music Awareness для модели</span></label><label class="checkbox_label"><input id="spc" type="checkbox"><span>Цвет от обложки</span></label><label>Режим<select id="spm" class="text_pole"><option value="auto">Auto</option><option value="inworld">In-world</option><option value="soundtrack">Soundtrack</option><option value="visual">Visual only</option></select></label><label>Реакция<select id="spr" class="text_pole"><option value="rare">Редко</option><option value="natural">Естественно</option><option value="active">Активно</option></select></label><div class="sp-note">Использует авторизацию официального Spotify extension. Lyrics-слот уже есть; источник строк подключим отдельно.</div><button id="spref" class="menu_button">↻ Обновить трек</button></div>`;h.appendChild(d);let B=(id,k,v=False)=>{let x=d.querySelector(id);x[v?'value':'checked']=S[k];x.onchange=()=>{S[k]=v?x.value:x.checked;save();render()}};B('#spe','enabled');B('#spw','widget');B('#spa','awareness');B('#spc','dynamicColor');B('#spm','mode',true);B('#spr','reaction',true);d.querySelector('#spref').onclick=poll}
async function init(){S=settings();ui();widget();render();await poll();setInterval(poll,8000);setInterval(tick,500)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,600));else setTimeout(init,600);
})();